"""add focus question table

Revision ID: 902bf8308147
Revises: 0d2b4bc8b80b
Create Date: 2016-07-16 19:06:05.800749

"""

# revision identifiers, used by Alembic.
revision = '902bf8308147'
down_revision = '0d2b4bc8b80b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focusquestion',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focusquestion')
    ### end Alembic commands ###
