"""add avatar_hash

Revision ID: c7b33faeb37e
Revises: 3956b3ad4f5f
Create Date: 2016-07-12 21:01:08.707325

"""

# revision identifiers, used by Alembic.
revision = 'c7b33faeb37e'
down_revision = '3956b3ad4f5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
